scalar DateTime
scalar UUID

type Meeting {
  id: UUID!
  userId: UUID!
  shareLink: String!
  startDate: DateTime!
  endDate: DateTime!
  createdAt: DateTime!
  updatedAt: DateTime!
}

input CreateMeetingInput {
  startDate: DateTime!
}

type Mutation {
  createMeeting(input: CreateMeetingInput!): Meeting!
}

type Query {
  meeting(id: ID!): Meeting!
  meetingsForUser: [Meeting!]!
}
