scalar DateTime
scalar UUID

enum MeetingState {
  PENDING
  SCHEDULED
  CANCELLED
}

type Meeting {
  id: UUID!
  state: MeetingState!
  invitedEmail: String
  userId: UUID!
  startDate: DateTime
  endDate: DateTime
  createdAt: DateTime!
  updatedAt: DateTime!
}

type Mutation {
  createMeeting: Meeting!
  deleteMeeting(id: UUID!): Boolean!
}

type Query {
  meeting(id: ID!): Meeting!
  meetingsForUser: [Meeting!]!
}
